version: 2

builds:
  - goos:
    - linux
    goarch:
    - amd64
    hooks:
      pre: go generate ./...

dockers:
  - image_templates:
    - ghcr.io/jamesmcdonald/cfdnsupdater:{{ .Tag }}
    - ghcr.io/jamesmcdonald/cfdnsupdater:latest
